package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ALIPAY_MODEL".
 */
@Entity
public class AlipayModel {

    @Id(autoincrement = true)
    private Long id;
    private String ALIPAY_ID;
    private String PARTNER_ID;
    private String SELLER_ID;
    private String REGION_CODE;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public AlipayModel() {
    }

    public AlipayModel(Long id) {
        this.id = id;
    }

    @Generated
    public AlipayModel(Long id, String ALIPAY_ID, String PARTNER_ID, String SELLER_ID, String REGION_CODE) {
        this.id = id;
        this.ALIPAY_ID = ALIPAY_ID;
        this.PARTNER_ID = PARTNER_ID;
        this.SELLER_ID = SELLER_ID;
        this.REGION_CODE = REGION_CODE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getALIPAY_ID() {
        return ALIPAY_ID;
    }

    public void setALIPAY_ID(String ALIPAY_ID) {
        this.ALIPAY_ID = ALIPAY_ID;
    }

    public String getPARTNER_ID() {
        return PARTNER_ID;
    }

    public void setPARTNER_ID(String PARTNER_ID) {
        this.PARTNER_ID = PARTNER_ID;
    }

    public String getSELLER_ID() {
        return SELLER_ID;
    }

    public void setSELLER_ID(String SELLER_ID) {
        this.SELLER_ID = SELLER_ID;
    }

    public String getREGION_CODE() {
        return REGION_CODE;
    }

    public void setREGION_CODE(String REGION_CODE) {
        this.REGION_CODE = REGION_CODE;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
