package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "BATCH".
 */
@Entity
public class Batch {

    @Id(autoincrement = true)
    private Long id;
    private String BATCH_ID;
    private String hdt_index;
    private String trans_type;
    private String trans_mode;
    private String voided;
    private String reversed;
    private String uploaded;
    private String proc_code;
    private String invoice_number;
    private String amount;
    private String tip_amount;
    private String time;
    private String date;
    private String year;
    private String org_mess_id;
    private String sys_trace_num;
    private String date_exp;
    private String retr_ref_num;
    private String auth_id_resp;
    private String resp_code;
    private String acct_number;
    private String person_name;
    private String original_amount;
    private String additional_data;
    private String payment_term_info;
    private String pri_acct_num;
    private String pos_ent_mode;
    private String NII;
    private String pos_cond_code;
    private String add_amount;
    private String card_type;
    private String card_sequence;
    private String ChipData;
    private String TVRValue;
    private String TSIValue;
    private String TransCryto;
    private String TotalScript71;
    private String TotalScript72;
    private String ScriptRslt71;
    private String ScriptRslt72;
    private String chAid;
    private String application_label;
    private String ui8ClsSchemeid;
    private String ui8SignReq;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Batch() {
    }

    public Batch(Long id) {
        this.id = id;
    }

    @Generated
    public Batch(Long id, String BATCH_ID, String hdt_index, String trans_type, String trans_mode, String voided, String reversed, String uploaded, String proc_code, String invoice_number, String amount, String tip_amount, String time, String date, String year, String org_mess_id, String sys_trace_num, String date_exp, String retr_ref_num, String auth_id_resp, String resp_code, String acct_number, String person_name, String original_amount, String additional_data, String payment_term_info, String pri_acct_num, String pos_ent_mode, String NII, String pos_cond_code, String add_amount, String card_type, String card_sequence, String ChipData, String TVRValue, String TSIValue, String TransCryto, String TotalScript71, String TotalScript72, String ScriptRslt71, String ScriptRslt72, String chAid, String application_label, String ui8ClsSchemeid, String ui8SignReq) {
        this.id = id;
        this.BATCH_ID = BATCH_ID;
        this.hdt_index = hdt_index;
        this.trans_type = trans_type;
        this.trans_mode = trans_mode;
        this.voided = voided;
        this.reversed = reversed;
        this.uploaded = uploaded;
        this.proc_code = proc_code;
        this.invoice_number = invoice_number;
        this.amount = amount;
        this.tip_amount = tip_amount;
        this.time = time;
        this.date = date;
        this.year = year;
        this.org_mess_id = org_mess_id;
        this.sys_trace_num = sys_trace_num;
        this.date_exp = date_exp;
        this.retr_ref_num = retr_ref_num;
        this.auth_id_resp = auth_id_resp;
        this.resp_code = resp_code;
        this.acct_number = acct_number;
        this.person_name = person_name;
        this.original_amount = original_amount;
        this.additional_data = additional_data;
        this.payment_term_info = payment_term_info;
        this.pri_acct_num = pri_acct_num;
        this.pos_ent_mode = pos_ent_mode;
        this.NII = NII;
        this.pos_cond_code = pos_cond_code;
        this.add_amount = add_amount;
        this.card_type = card_type;
        this.card_sequence = card_sequence;
        this.ChipData = ChipData;
        this.TVRValue = TVRValue;
        this.TSIValue = TSIValue;
        this.TransCryto = TransCryto;
        this.TotalScript71 = TotalScript71;
        this.TotalScript72 = TotalScript72;
        this.ScriptRslt71 = ScriptRslt71;
        this.ScriptRslt72 = ScriptRslt72;
        this.chAid = chAid;
        this.application_label = application_label;
        this.ui8ClsSchemeid = ui8ClsSchemeid;
        this.ui8SignReq = ui8SignReq;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBATCH_ID() {
        return BATCH_ID;
    }

    public void setBATCH_ID(String BATCH_ID) {
        this.BATCH_ID = BATCH_ID;
    }

    public String getHdt_index() {
        return hdt_index;
    }

    public void setHdt_index(String hdt_index) {
        this.hdt_index = hdt_index;
    }

    public String getTrans_type() {
        return trans_type;
    }

    public void setTrans_type(String trans_type) {
        this.trans_type = trans_type;
    }

    public String getTrans_mode() {
        return trans_mode;
    }

    public void setTrans_mode(String trans_mode) {
        this.trans_mode = trans_mode;
    }

    public String getVoided() {
        return voided;
    }

    public void setVoided(String voided) {
        this.voided = voided;
    }

    public String getReversed() {
        return reversed;
    }

    public void setReversed(String reversed) {
        this.reversed = reversed;
    }

    public String getUploaded() {
        return uploaded;
    }

    public void setUploaded(String uploaded) {
        this.uploaded = uploaded;
    }

    public String getProc_code() {
        return proc_code;
    }

    public void setProc_code(String proc_code) {
        this.proc_code = proc_code;
    }

    public String getInvoice_number() {
        return invoice_number;
    }

    public void setInvoice_number(String invoice_number) {
        this.invoice_number = invoice_number;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getTip_amount() {
        return tip_amount;
    }

    public void setTip_amount(String tip_amount) {
        this.tip_amount = tip_amount;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getOrg_mess_id() {
        return org_mess_id;
    }

    public void setOrg_mess_id(String org_mess_id) {
        this.org_mess_id = org_mess_id;
    }

    public String getSys_trace_num() {
        return sys_trace_num;
    }

    public void setSys_trace_num(String sys_trace_num) {
        this.sys_trace_num = sys_trace_num;
    }

    public String getDate_exp() {
        return date_exp;
    }

    public void setDate_exp(String date_exp) {
        this.date_exp = date_exp;
    }

    public String getRetr_ref_num() {
        return retr_ref_num;
    }

    public void setRetr_ref_num(String retr_ref_num) {
        this.retr_ref_num = retr_ref_num;
    }

    public String getAuth_id_resp() {
        return auth_id_resp;
    }

    public void setAuth_id_resp(String auth_id_resp) {
        this.auth_id_resp = auth_id_resp;
    }

    public String getResp_code() {
        return resp_code;
    }

    public void setResp_code(String resp_code) {
        this.resp_code = resp_code;
    }

    public String getAcct_number() {
        return acct_number;
    }

    public void setAcct_number(String acct_number) {
        this.acct_number = acct_number;
    }

    public String getPerson_name() {
        return person_name;
    }

    public void setPerson_name(String person_name) {
        this.person_name = person_name;
    }

    public String getOriginal_amount() {
        return original_amount;
    }

    public void setOriginal_amount(String original_amount) {
        this.original_amount = original_amount;
    }

    public String getAdditional_data() {
        return additional_data;
    }

    public void setAdditional_data(String additional_data) {
        this.additional_data = additional_data;
    }

    public String getPayment_term_info() {
        return payment_term_info;
    }

    public void setPayment_term_info(String payment_term_info) {
        this.payment_term_info = payment_term_info;
    }

    public String getPri_acct_num() {
        return pri_acct_num;
    }

    public void setPri_acct_num(String pri_acct_num) {
        this.pri_acct_num = pri_acct_num;
    }

    public String getPos_ent_mode() {
        return pos_ent_mode;
    }

    public void setPos_ent_mode(String pos_ent_mode) {
        this.pos_ent_mode = pos_ent_mode;
    }

    public String getNII() {
        return NII;
    }

    public void setNII(String NII) {
        this.NII = NII;
    }

    public String getPos_cond_code() {
        return pos_cond_code;
    }

    public void setPos_cond_code(String pos_cond_code) {
        this.pos_cond_code = pos_cond_code;
    }

    public String getAdd_amount() {
        return add_amount;
    }

    public void setAdd_amount(String add_amount) {
        this.add_amount = add_amount;
    }

    public String getCard_type() {
        return card_type;
    }

    public void setCard_type(String card_type) {
        this.card_type = card_type;
    }

    public String getCard_sequence() {
        return card_sequence;
    }

    public void setCard_sequence(String card_sequence) {
        this.card_sequence = card_sequence;
    }

    public String getChipData() {
        return ChipData;
    }

    public void setChipData(String ChipData) {
        this.ChipData = ChipData;
    }

    public String getTVRValue() {
        return TVRValue;
    }

    public void setTVRValue(String TVRValue) {
        this.TVRValue = TVRValue;
    }

    public String getTSIValue() {
        return TSIValue;
    }

    public void setTSIValue(String TSIValue) {
        this.TSIValue = TSIValue;
    }

    public String getTransCryto() {
        return TransCryto;
    }

    public void setTransCryto(String TransCryto) {
        this.TransCryto = TransCryto;
    }

    public String getTotalScript71() {
        return TotalScript71;
    }

    public void setTotalScript71(String TotalScript71) {
        this.TotalScript71 = TotalScript71;
    }

    public String getTotalScript72() {
        return TotalScript72;
    }

    public void setTotalScript72(String TotalScript72) {
        this.TotalScript72 = TotalScript72;
    }

    public String getScriptRslt71() {
        return ScriptRslt71;
    }

    public void setScriptRslt71(String ScriptRslt71) {
        this.ScriptRslt71 = ScriptRslt71;
    }

    public String getScriptRslt72() {
        return ScriptRslt72;
    }

    public void setScriptRslt72(String ScriptRslt72) {
        this.ScriptRslt72 = ScriptRslt72;
    }

    public String getChAid() {
        return chAid;
    }

    public void setChAid(String chAid) {
        this.chAid = chAid;
    }

    public String getApplication_label() {
        return application_label;
    }

    public void setApplication_label(String application_label) {
        this.application_label = application_label;
    }

    public String getUi8ClsSchemeid() {
        return ui8ClsSchemeid;
    }

    public void setUi8ClsSchemeid(String ui8ClsSchemeid) {
        this.ui8ClsSchemeid = ui8ClsSchemeid;
    }

    public String getUi8SignReq() {
        return ui8SignReq;
    }

    public void setUi8SignReq(String ui8SignReq) {
        this.ui8SignReq = ui8SignReq;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
