package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CARD_BIN_MODEL".
 */
@Entity
public class CardBinModel {

    @Id(autoincrement = true)
    private Long id;
    private String CDT_ID;
    private String CDT_LO_RANGE;
    private String CDT_HI_RANGE;
    private String CDT_HDT_REFERENCE;
    private String CDT_CARD_TYPE_ARRAY;
    private String CDT_CARD_NAME;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public CardBinModel() {
    }

    public CardBinModel(Long id) {
        this.id = id;
    }

    @Generated
    public CardBinModel(Long id, String CDT_ID, String CDT_LO_RANGE, String CDT_HI_RANGE, String CDT_HDT_REFERENCE, String CDT_CARD_TYPE_ARRAY, String CDT_CARD_NAME) {
        this.id = id;
        this.CDT_ID = CDT_ID;
        this.CDT_LO_RANGE = CDT_LO_RANGE;
        this.CDT_HI_RANGE = CDT_HI_RANGE;
        this.CDT_HDT_REFERENCE = CDT_HDT_REFERENCE;
        this.CDT_CARD_TYPE_ARRAY = CDT_CARD_TYPE_ARRAY;
        this.CDT_CARD_NAME = CDT_CARD_NAME;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCDT_ID() {
        return CDT_ID;
    }

    public void setCDT_ID(String CDT_ID) {
        this.CDT_ID = CDT_ID;
    }

    public String getCDT_LO_RANGE() {
        return CDT_LO_RANGE;
    }

    public void setCDT_LO_RANGE(String CDT_LO_RANGE) {
        this.CDT_LO_RANGE = CDT_LO_RANGE;
    }

    public String getCDT_HI_RANGE() {
        return CDT_HI_RANGE;
    }

    public void setCDT_HI_RANGE(String CDT_HI_RANGE) {
        this.CDT_HI_RANGE = CDT_HI_RANGE;
    }

    public String getCDT_HDT_REFERENCE() {
        return CDT_HDT_REFERENCE;
    }

    public void setCDT_HDT_REFERENCE(String CDT_HDT_REFERENCE) {
        this.CDT_HDT_REFERENCE = CDT_HDT_REFERENCE;
    }

    public String getCDT_CARD_TYPE_ARRAY() {
        return CDT_CARD_TYPE_ARRAY;
    }

    public void setCDT_CARD_TYPE_ARRAY(String CDT_CARD_TYPE_ARRAY) {
        this.CDT_CARD_TYPE_ARRAY = CDT_CARD_TYPE_ARRAY;
    }

    public String getCDT_CARD_NAME() {
        return CDT_CARD_NAME;
    }

    public void setCDT_CARD_NAME(String CDT_CARD_NAME) {
        this.CDT_CARD_NAME = CDT_CARD_NAME;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
