package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CARD_TYPE_TABLE".
 */
@Entity
public class CardTypeTable {

    @Id(autoincrement = true)
    private Long id;
    private String CTT_ID;
    private String CTT_CARD_TYPE;
    private String CTT_CARD_LABEL;
    private String CTT_CARD_FORMAT;
    private String CTT_MASK_FORMAT;
    private String CTT_MAGSTRIPE_FLOOR_LIMIT;
    private String CTT_DISABLE_LUHN;
    private String CTT_CUSTOM_OPTIONS;
    private String CTT_CVV_FDBC_ENABLE;
    private String CTT_PAN_MASK_ARRAY;
    private String CTT_EXPIRY_MASK_ARRAY;
    private String CTT_QPSL;
    private String CTT_DISABLE_EXPIRY_CHECK;
    private String CTT_MC501;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public CardTypeTable() {
    }

    public CardTypeTable(Long id) {
        this.id = id;
    }

    @Generated
    public CardTypeTable(Long id, String CTT_ID, String CTT_CARD_TYPE, String CTT_CARD_LABEL, String CTT_CARD_FORMAT, String CTT_MASK_FORMAT, String CTT_MAGSTRIPE_FLOOR_LIMIT, String CTT_DISABLE_LUHN, String CTT_CUSTOM_OPTIONS, String CTT_CVV_FDBC_ENABLE, String CTT_PAN_MASK_ARRAY, String CTT_EXPIRY_MASK_ARRAY, String CTT_QPSL, String CTT_DISABLE_EXPIRY_CHECK, String CTT_MC501) {
        this.id = id;
        this.CTT_ID = CTT_ID;
        this.CTT_CARD_TYPE = CTT_CARD_TYPE;
        this.CTT_CARD_LABEL = CTT_CARD_LABEL;
        this.CTT_CARD_FORMAT = CTT_CARD_FORMAT;
        this.CTT_MASK_FORMAT = CTT_MASK_FORMAT;
        this.CTT_MAGSTRIPE_FLOOR_LIMIT = CTT_MAGSTRIPE_FLOOR_LIMIT;
        this.CTT_DISABLE_LUHN = CTT_DISABLE_LUHN;
        this.CTT_CUSTOM_OPTIONS = CTT_CUSTOM_OPTIONS;
        this.CTT_CVV_FDBC_ENABLE = CTT_CVV_FDBC_ENABLE;
        this.CTT_PAN_MASK_ARRAY = CTT_PAN_MASK_ARRAY;
        this.CTT_EXPIRY_MASK_ARRAY = CTT_EXPIRY_MASK_ARRAY;
        this.CTT_QPSL = CTT_QPSL;
        this.CTT_DISABLE_EXPIRY_CHECK = CTT_DISABLE_EXPIRY_CHECK;
        this.CTT_MC501 = CTT_MC501;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCTT_ID() {
        return CTT_ID;
    }

    public void setCTT_ID(String CTT_ID) {
        this.CTT_ID = CTT_ID;
    }

    public String getCTT_CARD_TYPE() {
        return CTT_CARD_TYPE;
    }

    public void setCTT_CARD_TYPE(String CTT_CARD_TYPE) {
        this.CTT_CARD_TYPE = CTT_CARD_TYPE;
    }

    public String getCTT_CARD_LABEL() {
        return CTT_CARD_LABEL;
    }

    public void setCTT_CARD_LABEL(String CTT_CARD_LABEL) {
        this.CTT_CARD_LABEL = CTT_CARD_LABEL;
    }

    public String getCTT_CARD_FORMAT() {
        return CTT_CARD_FORMAT;
    }

    public void setCTT_CARD_FORMAT(String CTT_CARD_FORMAT) {
        this.CTT_CARD_FORMAT = CTT_CARD_FORMAT;
    }

    public String getCTT_MASK_FORMAT() {
        return CTT_MASK_FORMAT;
    }

    public void setCTT_MASK_FORMAT(String CTT_MASK_FORMAT) {
        this.CTT_MASK_FORMAT = CTT_MASK_FORMAT;
    }

    public String getCTT_MAGSTRIPE_FLOOR_LIMIT() {
        return CTT_MAGSTRIPE_FLOOR_LIMIT;
    }

    public void setCTT_MAGSTRIPE_FLOOR_LIMIT(String CTT_MAGSTRIPE_FLOOR_LIMIT) {
        this.CTT_MAGSTRIPE_FLOOR_LIMIT = CTT_MAGSTRIPE_FLOOR_LIMIT;
    }

    public String getCTT_DISABLE_LUHN() {
        return CTT_DISABLE_LUHN;
    }

    public void setCTT_DISABLE_LUHN(String CTT_DISABLE_LUHN) {
        this.CTT_DISABLE_LUHN = CTT_DISABLE_LUHN;
    }

    public String getCTT_CUSTOM_OPTIONS() {
        return CTT_CUSTOM_OPTIONS;
    }

    public void setCTT_CUSTOM_OPTIONS(String CTT_CUSTOM_OPTIONS) {
        this.CTT_CUSTOM_OPTIONS = CTT_CUSTOM_OPTIONS;
    }

    public String getCTT_CVV_FDBC_ENABLE() {
        return CTT_CVV_FDBC_ENABLE;
    }

    public void setCTT_CVV_FDBC_ENABLE(String CTT_CVV_FDBC_ENABLE) {
        this.CTT_CVV_FDBC_ENABLE = CTT_CVV_FDBC_ENABLE;
    }

    public String getCTT_PAN_MASK_ARRAY() {
        return CTT_PAN_MASK_ARRAY;
    }

    public void setCTT_PAN_MASK_ARRAY(String CTT_PAN_MASK_ARRAY) {
        this.CTT_PAN_MASK_ARRAY = CTT_PAN_MASK_ARRAY;
    }

    public String getCTT_EXPIRY_MASK_ARRAY() {
        return CTT_EXPIRY_MASK_ARRAY;
    }

    public void setCTT_EXPIRY_MASK_ARRAY(String CTT_EXPIRY_MASK_ARRAY) {
        this.CTT_EXPIRY_MASK_ARRAY = CTT_EXPIRY_MASK_ARRAY;
    }

    public String getCTT_QPSL() {
        return CTT_QPSL;
    }

    public void setCTT_QPSL(String CTT_QPSL) {
        this.CTT_QPSL = CTT_QPSL;
    }

    public String getCTT_DISABLE_EXPIRY_CHECK() {
        return CTT_DISABLE_EXPIRY_CHECK;
    }

    public void setCTT_DISABLE_EXPIRY_CHECK(String CTT_DISABLE_EXPIRY_CHECK) {
        this.CTT_DISABLE_EXPIRY_CHECK = CTT_DISABLE_EXPIRY_CHECK;
    }

    public String getCTT_MC501() {
        return CTT_MC501;
    }

    public void setCTT_MC501(String CTT_MC501) {
        this.CTT_MC501 = CTT_MC501;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
