package com.mobileeftpos.android.eftpos.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        HostModelDao.createTable(db, ifNotExists);
        CardBinModelDao.createTable(db, ifNotExists);
        CardTypeModelDao.createTable(db, ifNotExists);
        PasswordModelDao.createTable(db, ifNotExists);
        BatchModelDao.createTable(db, ifNotExists);
        AlipayModelDao.createTable(db, ifNotExists);
        ReceiptModelDao.createTable(db, ifNotExists);
        UtilityModelDao.createTable(db, ifNotExists);
        MaskingModelDao.createTable(db, ifNotExists);
        LimitModelDao.createTable(db, ifNotExists);
        EthernetModelDao.createTable(db, ifNotExists);
        CurrencyModelDao.createTable(db, ifNotExists);
        TransactionControlModelDao.createTable(db, ifNotExists);
        EzlinkModelDao.createTable(db, ifNotExists);
        CommsModelDao.createTable(db, ifNotExists);
        TraceModelDao.createTable(db, ifNotExists);
        HTTModelDao.createTable(db, ifNotExists);
        MerchantModelDao.createTable(db, ifNotExists);
        ReportModelDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        HostModelDao.dropTable(db, ifExists);
        CardBinModelDao.dropTable(db, ifExists);
        CardTypeModelDao.dropTable(db, ifExists);
        PasswordModelDao.dropTable(db, ifExists);
        BatchModelDao.dropTable(db, ifExists);
        AlipayModelDao.dropTable(db, ifExists);
        ReceiptModelDao.dropTable(db, ifExists);
        UtilityModelDao.dropTable(db, ifExists);
        MaskingModelDao.dropTable(db, ifExists);
        LimitModelDao.dropTable(db, ifExists);
        EthernetModelDao.dropTable(db, ifExists);
        CurrencyModelDao.dropTable(db, ifExists);
        TransactionControlModelDao.dropTable(db, ifExists);
        EzlinkModelDao.dropTable(db, ifExists);
        CommsModelDao.dropTable(db, ifExists);
        TraceModelDao.dropTable(db, ifExists);
        HTTModelDao.dropTable(db, ifExists);
        MerchantModelDao.dropTable(db, ifExists);
        ReportModelDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(HostModelDao.class);
        registerDaoClass(CardBinModelDao.class);
        registerDaoClass(CardTypeModelDao.class);
        registerDaoClass(PasswordModelDao.class);
        registerDaoClass(BatchModelDao.class);
        registerDaoClass(AlipayModelDao.class);
        registerDaoClass(ReceiptModelDao.class);
        registerDaoClass(UtilityModelDao.class);
        registerDaoClass(MaskingModelDao.class);
        registerDaoClass(LimitModelDao.class);
        registerDaoClass(EthernetModelDao.class);
        registerDaoClass(CurrencyModelDao.class);
        registerDaoClass(TransactionControlModelDao.class);
        registerDaoClass(EzlinkModelDao.class);
        registerDaoClass(CommsModelDao.class);
        registerDaoClass(TraceModelDao.class);
        registerDaoClass(HTTModelDao.class);
        registerDaoClass(MerchantModelDao.class);
        registerDaoClass(ReportModelDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
