package com.mobileeftpos.android.eftpos.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mobileeftpos.android.eftpos.db.HostModel;
import com.mobileeftpos.android.eftpos.db.CardBinModel;
import com.mobileeftpos.android.eftpos.db.CardTypeModel;
import com.mobileeftpos.android.eftpos.db.PasswordModel;
import com.mobileeftpos.android.eftpos.db.BatchModel;
import com.mobileeftpos.android.eftpos.db.AlipayModel;
import com.mobileeftpos.android.eftpos.db.ReceiptModel;
import com.mobileeftpos.android.eftpos.db.UtilityModel;
import com.mobileeftpos.android.eftpos.db.MaskingModel;
import com.mobileeftpos.android.eftpos.db.LimitModel;
import com.mobileeftpos.android.eftpos.db.EthernetModel;
import com.mobileeftpos.android.eftpos.db.CurrencyModel;
import com.mobileeftpos.android.eftpos.db.TransactionControlModel;
import com.mobileeftpos.android.eftpos.db.EzlinkModel;
import com.mobileeftpos.android.eftpos.db.CommsModel;
import com.mobileeftpos.android.eftpos.db.TraceModel;
import com.mobileeftpos.android.eftpos.db.HTTModel;
import com.mobileeftpos.android.eftpos.db.MerchantModel;
import com.mobileeftpos.android.eftpos.db.ReportModel;

import com.mobileeftpos.android.eftpos.db.HostModelDao;
import com.mobileeftpos.android.eftpos.db.CardBinModelDao;
import com.mobileeftpos.android.eftpos.db.CardTypeModelDao;
import com.mobileeftpos.android.eftpos.db.PasswordModelDao;
import com.mobileeftpos.android.eftpos.db.BatchModelDao;
import com.mobileeftpos.android.eftpos.db.AlipayModelDao;
import com.mobileeftpos.android.eftpos.db.ReceiptModelDao;
import com.mobileeftpos.android.eftpos.db.UtilityModelDao;
import com.mobileeftpos.android.eftpos.db.MaskingModelDao;
import com.mobileeftpos.android.eftpos.db.LimitModelDao;
import com.mobileeftpos.android.eftpos.db.EthernetModelDao;
import com.mobileeftpos.android.eftpos.db.CurrencyModelDao;
import com.mobileeftpos.android.eftpos.db.TransactionControlModelDao;
import com.mobileeftpos.android.eftpos.db.EzlinkModelDao;
import com.mobileeftpos.android.eftpos.db.CommsModelDao;
import com.mobileeftpos.android.eftpos.db.TraceModelDao;
import com.mobileeftpos.android.eftpos.db.HTTModelDao;
import com.mobileeftpos.android.eftpos.db.MerchantModelDao;
import com.mobileeftpos.android.eftpos.db.ReportModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hostModelDaoConfig;
    private final DaoConfig cardBinModelDaoConfig;
    private final DaoConfig cardTypeModelDaoConfig;
    private final DaoConfig passwordModelDaoConfig;
    private final DaoConfig batchModelDaoConfig;
    private final DaoConfig alipayModelDaoConfig;
    private final DaoConfig receiptModelDaoConfig;
    private final DaoConfig utilityModelDaoConfig;
    private final DaoConfig maskingModelDaoConfig;
    private final DaoConfig limitModelDaoConfig;
    private final DaoConfig ethernetModelDaoConfig;
    private final DaoConfig currencyModelDaoConfig;
    private final DaoConfig transactionControlModelDaoConfig;
    private final DaoConfig ezlinkModelDaoConfig;
    private final DaoConfig commsModelDaoConfig;
    private final DaoConfig traceModelDaoConfig;
    private final DaoConfig hTTModelDaoConfig;
    private final DaoConfig merchantModelDaoConfig;
    private final DaoConfig reportModelDaoConfig;

    private final HostModelDao hostModelDao;
    private final CardBinModelDao cardBinModelDao;
    private final CardTypeModelDao cardTypeModelDao;
    private final PasswordModelDao passwordModelDao;
    private final BatchModelDao batchModelDao;
    private final AlipayModelDao alipayModelDao;
    private final ReceiptModelDao receiptModelDao;
    private final UtilityModelDao utilityModelDao;
    private final MaskingModelDao maskingModelDao;
    private final LimitModelDao limitModelDao;
    private final EthernetModelDao ethernetModelDao;
    private final CurrencyModelDao currencyModelDao;
    private final TransactionControlModelDao transactionControlModelDao;
    private final EzlinkModelDao ezlinkModelDao;
    private final CommsModelDao commsModelDao;
    private final TraceModelDao traceModelDao;
    private final HTTModelDao hTTModelDao;
    private final MerchantModelDao merchantModelDao;
    private final ReportModelDao reportModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hostModelDaoConfig = daoConfigMap.get(HostModelDao.class).clone();
        hostModelDaoConfig.initIdentityScope(type);

        cardBinModelDaoConfig = daoConfigMap.get(CardBinModelDao.class).clone();
        cardBinModelDaoConfig.initIdentityScope(type);

        cardTypeModelDaoConfig = daoConfigMap.get(CardTypeModelDao.class).clone();
        cardTypeModelDaoConfig.initIdentityScope(type);

        passwordModelDaoConfig = daoConfigMap.get(PasswordModelDao.class).clone();
        passwordModelDaoConfig.initIdentityScope(type);

        batchModelDaoConfig = daoConfigMap.get(BatchModelDao.class).clone();
        batchModelDaoConfig.initIdentityScope(type);

        alipayModelDaoConfig = daoConfigMap.get(AlipayModelDao.class).clone();
        alipayModelDaoConfig.initIdentityScope(type);

        receiptModelDaoConfig = daoConfigMap.get(ReceiptModelDao.class).clone();
        receiptModelDaoConfig.initIdentityScope(type);

        utilityModelDaoConfig = daoConfigMap.get(UtilityModelDao.class).clone();
        utilityModelDaoConfig.initIdentityScope(type);

        maskingModelDaoConfig = daoConfigMap.get(MaskingModelDao.class).clone();
        maskingModelDaoConfig.initIdentityScope(type);

        limitModelDaoConfig = daoConfigMap.get(LimitModelDao.class).clone();
        limitModelDaoConfig.initIdentityScope(type);

        ethernetModelDaoConfig = daoConfigMap.get(EthernetModelDao.class).clone();
        ethernetModelDaoConfig.initIdentityScope(type);

        currencyModelDaoConfig = daoConfigMap.get(CurrencyModelDao.class).clone();
        currencyModelDaoConfig.initIdentityScope(type);

        transactionControlModelDaoConfig = daoConfigMap.get(TransactionControlModelDao.class).clone();
        transactionControlModelDaoConfig.initIdentityScope(type);

        ezlinkModelDaoConfig = daoConfigMap.get(EzlinkModelDao.class).clone();
        ezlinkModelDaoConfig.initIdentityScope(type);

        commsModelDaoConfig = daoConfigMap.get(CommsModelDao.class).clone();
        commsModelDaoConfig.initIdentityScope(type);

        traceModelDaoConfig = daoConfigMap.get(TraceModelDao.class).clone();
        traceModelDaoConfig.initIdentityScope(type);

        hTTModelDaoConfig = daoConfigMap.get(HTTModelDao.class).clone();
        hTTModelDaoConfig.initIdentityScope(type);

        merchantModelDaoConfig = daoConfigMap.get(MerchantModelDao.class).clone();
        merchantModelDaoConfig.initIdentityScope(type);

        reportModelDaoConfig = daoConfigMap.get(ReportModelDao.class).clone();
        reportModelDaoConfig.initIdentityScope(type);

        hostModelDao = new HostModelDao(hostModelDaoConfig, this);
        cardBinModelDao = new CardBinModelDao(cardBinModelDaoConfig, this);
        cardTypeModelDao = new CardTypeModelDao(cardTypeModelDaoConfig, this);
        passwordModelDao = new PasswordModelDao(passwordModelDaoConfig, this);
        batchModelDao = new BatchModelDao(batchModelDaoConfig, this);
        alipayModelDao = new AlipayModelDao(alipayModelDaoConfig, this);
        receiptModelDao = new ReceiptModelDao(receiptModelDaoConfig, this);
        utilityModelDao = new UtilityModelDao(utilityModelDaoConfig, this);
        maskingModelDao = new MaskingModelDao(maskingModelDaoConfig, this);
        limitModelDao = new LimitModelDao(limitModelDaoConfig, this);
        ethernetModelDao = new EthernetModelDao(ethernetModelDaoConfig, this);
        currencyModelDao = new CurrencyModelDao(currencyModelDaoConfig, this);
        transactionControlModelDao = new TransactionControlModelDao(transactionControlModelDaoConfig, this);
        ezlinkModelDao = new EzlinkModelDao(ezlinkModelDaoConfig, this);
        commsModelDao = new CommsModelDao(commsModelDaoConfig, this);
        traceModelDao = new TraceModelDao(traceModelDaoConfig, this);
        hTTModelDao = new HTTModelDao(hTTModelDaoConfig, this);
        merchantModelDao = new MerchantModelDao(merchantModelDaoConfig, this);
        reportModelDao = new ReportModelDao(reportModelDaoConfig, this);

        registerDao(HostModel.class, hostModelDao);
        registerDao(CardBinModel.class, cardBinModelDao);
        registerDao(CardTypeModel.class, cardTypeModelDao);
        registerDao(PasswordModel.class, passwordModelDao);
        registerDao(BatchModel.class, batchModelDao);
        registerDao(AlipayModel.class, alipayModelDao);
        registerDao(ReceiptModel.class, receiptModelDao);
        registerDao(UtilityModel.class, utilityModelDao);
        registerDao(MaskingModel.class, maskingModelDao);
        registerDao(LimitModel.class, limitModelDao);
        registerDao(EthernetModel.class, ethernetModelDao);
        registerDao(CurrencyModel.class, currencyModelDao);
        registerDao(TransactionControlModel.class, transactionControlModelDao);
        registerDao(EzlinkModel.class, ezlinkModelDao);
        registerDao(CommsModel.class, commsModelDao);
        registerDao(TraceModel.class, traceModelDao);
        registerDao(HTTModel.class, hTTModelDao);
        registerDao(MerchantModel.class, merchantModelDao);
        registerDao(ReportModel.class, reportModelDao);
    }
    
    public void clear() {
        hostModelDaoConfig.clearIdentityScope();
        cardBinModelDaoConfig.clearIdentityScope();
        cardTypeModelDaoConfig.clearIdentityScope();
        passwordModelDaoConfig.clearIdentityScope();
        batchModelDaoConfig.clearIdentityScope();
        alipayModelDaoConfig.clearIdentityScope();
        receiptModelDaoConfig.clearIdentityScope();
        utilityModelDaoConfig.clearIdentityScope();
        maskingModelDaoConfig.clearIdentityScope();
        limitModelDaoConfig.clearIdentityScope();
        ethernetModelDaoConfig.clearIdentityScope();
        currencyModelDaoConfig.clearIdentityScope();
        transactionControlModelDaoConfig.clearIdentityScope();
        ezlinkModelDaoConfig.clearIdentityScope();
        commsModelDaoConfig.clearIdentityScope();
        traceModelDaoConfig.clearIdentityScope();
        hTTModelDaoConfig.clearIdentityScope();
        merchantModelDaoConfig.clearIdentityScope();
        reportModelDaoConfig.clearIdentityScope();
    }

    public HostModelDao getHostModelDao() {
        return hostModelDao;
    }

    public CardBinModelDao getCardBinModelDao() {
        return cardBinModelDao;
    }

    public CardTypeModelDao getCardTypeModelDao() {
        return cardTypeModelDao;
    }

    public PasswordModelDao getPasswordModelDao() {
        return passwordModelDao;
    }

    public BatchModelDao getBatchModelDao() {
        return batchModelDao;
    }

    public AlipayModelDao getAlipayModelDao() {
        return alipayModelDao;
    }

    public ReceiptModelDao getReceiptModelDao() {
        return receiptModelDao;
    }

    public UtilityModelDao getUtilityModelDao() {
        return utilityModelDao;
    }

    public MaskingModelDao getMaskingModelDao() {
        return maskingModelDao;
    }

    public LimitModelDao getLimitModelDao() {
        return limitModelDao;
    }

    public EthernetModelDao getEthernetModelDao() {
        return ethernetModelDao;
    }

    public CurrencyModelDao getCurrencyModelDao() {
        return currencyModelDao;
    }

    public TransactionControlModelDao getTransactionControlModelDao() {
        return transactionControlModelDao;
    }

    public EzlinkModelDao getEzlinkModelDao() {
        return ezlinkModelDao;
    }

    public CommsModelDao getCommsModelDao() {
        return commsModelDao;
    }

    public TraceModelDao getTraceModelDao() {
        return traceModelDao;
    }

    public HTTModelDao getHTTModelDao() {
        return hTTModelDao;
    }

    public MerchantModelDao getMerchantModelDao() {
        return merchantModelDao;
    }

    public ReportModelDao getReportModelDao() {
        return reportModelDao;
    }

}
