package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ETHERNET_MODEL".
 */
@Entity
public class EthernetModel {

    @Id(autoincrement = true)
    private Long id;
    private String ETHERNET_ID;
    private String LOCAL_IP;
    private String SUBNET_MASK;
    private String GATEWAY;
    private String DNS1;
    private String DNS2;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public EthernetModel() {
    }

    public EthernetModel(Long id) {
        this.id = id;
    }

    @Generated
    public EthernetModel(Long id, String ETHERNET_ID, String LOCAL_IP, String SUBNET_MASK, String GATEWAY, String DNS1, String DNS2) {
        this.id = id;
        this.ETHERNET_ID = ETHERNET_ID;
        this.LOCAL_IP = LOCAL_IP;
        this.SUBNET_MASK = SUBNET_MASK;
        this.GATEWAY = GATEWAY;
        this.DNS1 = DNS1;
        this.DNS2 = DNS2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getETHERNET_ID() {
        return ETHERNET_ID;
    }

    public void setETHERNET_ID(String ETHERNET_ID) {
        this.ETHERNET_ID = ETHERNET_ID;
    }

    public String getLOCAL_IP() {
        return LOCAL_IP;
    }

    public void setLOCAL_IP(String LOCAL_IP) {
        this.LOCAL_IP = LOCAL_IP;
    }

    public String getSUBNET_MASK() {
        return SUBNET_MASK;
    }

    public void setSUBNET_MASK(String SUBNET_MASK) {
        this.SUBNET_MASK = SUBNET_MASK;
    }

    public String getGATEWAY() {
        return GATEWAY;
    }

    public void setGATEWAY(String GATEWAY) {
        this.GATEWAY = GATEWAY;
    }

    public String getDNS1() {
        return DNS1;
    }

    public void setDNS1(String DNS1) {
        this.DNS1 = DNS1;
    }

    public String getDNS2() {
        return DNS2;
    }

    public void setDNS2(String DNS2) {
        this.DNS2 = DNS2;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
