package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EZLINK_MODEL".
 */
@Entity
public class EzlinkModel {

    @Id(autoincrement = true)
    private Long id;
    private String Ezlink_ID;
    private String EZLINK_ENABLE;
    private String EZLINK_SAM_KEY;
    private String EZLINK_PAYMENT_TRP;
    private String EZLINK_TOPUP_TRP;
    private String EZLINK_PAYMENT_DEVICE_TYPE;
    private String EZLINK_TOPUP_DEVICE_TYPE;
    private String EZLINK_BLACK_LIST_LAST_UPDATE;
    private String EZLINK_TOPUP_PAYMENT_MODE;
    private String EZLINK_PAYMENT_MAC_KEY;
    private String EZLINK_TOPUP_MAC_KEY;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public EzlinkModel() {
    }

    public EzlinkModel(Long id) {
        this.id = id;
    }

    @Generated
    public EzlinkModel(Long id, String Ezlink_ID, String EZLINK_ENABLE, String EZLINK_SAM_KEY, String EZLINK_PAYMENT_TRP, String EZLINK_TOPUP_TRP, String EZLINK_PAYMENT_DEVICE_TYPE, String EZLINK_TOPUP_DEVICE_TYPE, String EZLINK_BLACK_LIST_LAST_UPDATE, String EZLINK_TOPUP_PAYMENT_MODE, String EZLINK_PAYMENT_MAC_KEY, String EZLINK_TOPUP_MAC_KEY) {
        this.id = id;
        this.Ezlink_ID = Ezlink_ID;
        this.EZLINK_ENABLE = EZLINK_ENABLE;
        this.EZLINK_SAM_KEY = EZLINK_SAM_KEY;
        this.EZLINK_PAYMENT_TRP = EZLINK_PAYMENT_TRP;
        this.EZLINK_TOPUP_TRP = EZLINK_TOPUP_TRP;
        this.EZLINK_PAYMENT_DEVICE_TYPE = EZLINK_PAYMENT_DEVICE_TYPE;
        this.EZLINK_TOPUP_DEVICE_TYPE = EZLINK_TOPUP_DEVICE_TYPE;
        this.EZLINK_BLACK_LIST_LAST_UPDATE = EZLINK_BLACK_LIST_LAST_UPDATE;
        this.EZLINK_TOPUP_PAYMENT_MODE = EZLINK_TOPUP_PAYMENT_MODE;
        this.EZLINK_PAYMENT_MAC_KEY = EZLINK_PAYMENT_MAC_KEY;
        this.EZLINK_TOPUP_MAC_KEY = EZLINK_TOPUP_MAC_KEY;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEzlink_ID() {
        return Ezlink_ID;
    }

    public void setEzlink_ID(String Ezlink_ID) {
        this.Ezlink_ID = Ezlink_ID;
    }

    public String getEZLINK_ENABLE() {
        return EZLINK_ENABLE;
    }

    public void setEZLINK_ENABLE(String EZLINK_ENABLE) {
        this.EZLINK_ENABLE = EZLINK_ENABLE;
    }

    public String getEZLINK_SAM_KEY() {
        return EZLINK_SAM_KEY;
    }

    public void setEZLINK_SAM_KEY(String EZLINK_SAM_KEY) {
        this.EZLINK_SAM_KEY = EZLINK_SAM_KEY;
    }

    public String getEZLINK_PAYMENT_TRP() {
        return EZLINK_PAYMENT_TRP;
    }

    public void setEZLINK_PAYMENT_TRP(String EZLINK_PAYMENT_TRP) {
        this.EZLINK_PAYMENT_TRP = EZLINK_PAYMENT_TRP;
    }

    public String getEZLINK_TOPUP_TRP() {
        return EZLINK_TOPUP_TRP;
    }

    public void setEZLINK_TOPUP_TRP(String EZLINK_TOPUP_TRP) {
        this.EZLINK_TOPUP_TRP = EZLINK_TOPUP_TRP;
    }

    public String getEZLINK_PAYMENT_DEVICE_TYPE() {
        return EZLINK_PAYMENT_DEVICE_TYPE;
    }

    public void setEZLINK_PAYMENT_DEVICE_TYPE(String EZLINK_PAYMENT_DEVICE_TYPE) {
        this.EZLINK_PAYMENT_DEVICE_TYPE = EZLINK_PAYMENT_DEVICE_TYPE;
    }

    public String getEZLINK_TOPUP_DEVICE_TYPE() {
        return EZLINK_TOPUP_DEVICE_TYPE;
    }

    public void setEZLINK_TOPUP_DEVICE_TYPE(String EZLINK_TOPUP_DEVICE_TYPE) {
        this.EZLINK_TOPUP_DEVICE_TYPE = EZLINK_TOPUP_DEVICE_TYPE;
    }

    public String getEZLINK_BLACK_LIST_LAST_UPDATE() {
        return EZLINK_BLACK_LIST_LAST_UPDATE;
    }

    public void setEZLINK_BLACK_LIST_LAST_UPDATE(String EZLINK_BLACK_LIST_LAST_UPDATE) {
        this.EZLINK_BLACK_LIST_LAST_UPDATE = EZLINK_BLACK_LIST_LAST_UPDATE;
    }

    public String getEZLINK_TOPUP_PAYMENT_MODE() {
        return EZLINK_TOPUP_PAYMENT_MODE;
    }

    public void setEZLINK_TOPUP_PAYMENT_MODE(String EZLINK_TOPUP_PAYMENT_MODE) {
        this.EZLINK_TOPUP_PAYMENT_MODE = EZLINK_TOPUP_PAYMENT_MODE;
    }

    public String getEZLINK_PAYMENT_MAC_KEY() {
        return EZLINK_PAYMENT_MAC_KEY;
    }

    public void setEZLINK_PAYMENT_MAC_KEY(String EZLINK_PAYMENT_MAC_KEY) {
        this.EZLINK_PAYMENT_MAC_KEY = EZLINK_PAYMENT_MAC_KEY;
    }

    public String getEZLINK_TOPUP_MAC_KEY() {
        return EZLINK_TOPUP_MAC_KEY;
    }

    public void setEZLINK_TOPUP_MAC_KEY(String EZLINK_TOPUP_MAC_KEY) {
        this.EZLINK_TOPUP_MAC_KEY = EZLINK_TOPUP_MAC_KEY;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
