package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "HTTMODEL".
 */
@Entity
public class HTTModel {

    @Id(autoincrement = true)
    private Long id;
    private String HTT_ID;
    private String TRANSMISSION_MODE;
    private String CONNECTION_TIMEOUT;
    private String REDIAL_TIMEOUT;
    private String PABX;
    private String MODEM_STRING;
    private String REPORTTABLE_ID;
    private String DETAILED_REPORT;
    private String TIP_REPORT;
    private String TOTAL_REPORT;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public HTTModel() {
    }

    public HTTModel(Long id) {
        this.id = id;
    }

    @Generated
    public HTTModel(Long id, String HTT_ID, String TRANSMISSION_MODE, String CONNECTION_TIMEOUT, String REDIAL_TIMEOUT, String PABX, String MODEM_STRING, String REPORTTABLE_ID, String DETAILED_REPORT, String TIP_REPORT, String TOTAL_REPORT) {
        this.id = id;
        this.HTT_ID = HTT_ID;
        this.TRANSMISSION_MODE = TRANSMISSION_MODE;
        this.CONNECTION_TIMEOUT = CONNECTION_TIMEOUT;
        this.REDIAL_TIMEOUT = REDIAL_TIMEOUT;
        this.PABX = PABX;
        this.MODEM_STRING = MODEM_STRING;
        this.REPORTTABLE_ID = REPORTTABLE_ID;
        this.DETAILED_REPORT = DETAILED_REPORT;
        this.TIP_REPORT = TIP_REPORT;
        this.TOTAL_REPORT = TOTAL_REPORT;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHTT_ID() {
        return HTT_ID;
    }

    public void setHTT_ID(String HTT_ID) {
        this.HTT_ID = HTT_ID;
    }

    public String getTRANSMISSION_MODE() {
        return TRANSMISSION_MODE;
    }

    public void setTRANSMISSION_MODE(String TRANSMISSION_MODE) {
        this.TRANSMISSION_MODE = TRANSMISSION_MODE;
    }

    public String getCONNECTION_TIMEOUT() {
        return CONNECTION_TIMEOUT;
    }

    public void setCONNECTION_TIMEOUT(String CONNECTION_TIMEOUT) {
        this.CONNECTION_TIMEOUT = CONNECTION_TIMEOUT;
    }

    public String getREDIAL_TIMEOUT() {
        return REDIAL_TIMEOUT;
    }

    public void setREDIAL_TIMEOUT(String REDIAL_TIMEOUT) {
        this.REDIAL_TIMEOUT = REDIAL_TIMEOUT;
    }

    public String getPABX() {
        return PABX;
    }

    public void setPABX(String PABX) {
        this.PABX = PABX;
    }

    public String getMODEM_STRING() {
        return MODEM_STRING;
    }

    public void setMODEM_STRING(String MODEM_STRING) {
        this.MODEM_STRING = MODEM_STRING;
    }

    public String getREPORTTABLE_ID() {
        return REPORTTABLE_ID;
    }

    public void setREPORTTABLE_ID(String REPORTTABLE_ID) {
        this.REPORTTABLE_ID = REPORTTABLE_ID;
    }

    public String getDETAILED_REPORT() {
        return DETAILED_REPORT;
    }

    public void setDETAILED_REPORT(String DETAILED_REPORT) {
        this.DETAILED_REPORT = DETAILED_REPORT;
    }

    public String getTIP_REPORT() {
        return TIP_REPORT;
    }

    public void setTIP_REPORT(String TIP_REPORT) {
        this.TIP_REPORT = TIP_REPORT;
    }

    public String getTOTAL_REPORT() {
        return TOTAL_REPORT;
    }

    public void setTOTAL_REPORT(String TOTAL_REPORT) {
        this.TOTAL_REPORT = TOTAL_REPORT;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
