package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LIMIT_TABLE".
 */
@Entity
public class LimitTable {

    @Id(autoincrement = true)
    private Long id;
    private String LIMIT_ID;
    private String MAXIMUM_SALE_AMOUNT;
    private String MAXIMUM_OFFLINE_AMOUNT;
    private String MAXIMUM_PREAUTH_AMOUNT;
    private String MAXIMUM_REFUND_AMOUNT;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public LimitTable() {
    }

    public LimitTable(Long id) {
        this.id = id;
    }

    @Generated
    public LimitTable(Long id, String LIMIT_ID, String MAXIMUM_SALE_AMOUNT, String MAXIMUM_OFFLINE_AMOUNT, String MAXIMUM_PREAUTH_AMOUNT, String MAXIMUM_REFUND_AMOUNT) {
        this.id = id;
        this.LIMIT_ID = LIMIT_ID;
        this.MAXIMUM_SALE_AMOUNT = MAXIMUM_SALE_AMOUNT;
        this.MAXIMUM_OFFLINE_AMOUNT = MAXIMUM_OFFLINE_AMOUNT;
        this.MAXIMUM_PREAUTH_AMOUNT = MAXIMUM_PREAUTH_AMOUNT;
        this.MAXIMUM_REFUND_AMOUNT = MAXIMUM_REFUND_AMOUNT;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLIMIT_ID() {
        return LIMIT_ID;
    }

    public void setLIMIT_ID(String LIMIT_ID) {
        this.LIMIT_ID = LIMIT_ID;
    }

    public String getMAXIMUM_SALE_AMOUNT() {
        return MAXIMUM_SALE_AMOUNT;
    }

    public void setMAXIMUM_SALE_AMOUNT(String MAXIMUM_SALE_AMOUNT) {
        this.MAXIMUM_SALE_AMOUNT = MAXIMUM_SALE_AMOUNT;
    }

    public String getMAXIMUM_OFFLINE_AMOUNT() {
        return MAXIMUM_OFFLINE_AMOUNT;
    }

    public void setMAXIMUM_OFFLINE_AMOUNT(String MAXIMUM_OFFLINE_AMOUNT) {
        this.MAXIMUM_OFFLINE_AMOUNT = MAXIMUM_OFFLINE_AMOUNT;
    }

    public String getMAXIMUM_PREAUTH_AMOUNT() {
        return MAXIMUM_PREAUTH_AMOUNT;
    }

    public void setMAXIMUM_PREAUTH_AMOUNT(String MAXIMUM_PREAUTH_AMOUNT) {
        this.MAXIMUM_PREAUTH_AMOUNT = MAXIMUM_PREAUTH_AMOUNT;
    }

    public String getMAXIMUM_REFUND_AMOUNT() {
        return MAXIMUM_REFUND_AMOUNT;
    }

    public void setMAXIMUM_REFUND_AMOUNT(String MAXIMUM_REFUND_AMOUNT) {
        this.MAXIMUM_REFUND_AMOUNT = MAXIMUM_REFUND_AMOUNT;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
