package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PASSWORD_MODEL".
 */
@Entity
public class PasswordModel {

    @Id(autoincrement = true)
    private Long id;
    private String PWD_ID;
    private String DEFAULT_PASSWORD;
    private String REFUND_PASWORD;
    private String TIP_ADJUST_PASSWORD;
    private String PRE_AUTH_PASSWORD;
    private String BALANCE_PASSWORD;
    private String OFFLINE_PASSWORD;
    private String SETTLEMENT_PASSWORD;
    private String EDITOR_PASSWORD;
    private String VOID_PASSWORD;
    private String MANUAL_ENTRY_PASSWORD;
    private String CASH_ADVANCED_PASSWORD;
    private String TERMINAL_POWERON_PASSWORD;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PasswordModel() {
    }

    public PasswordModel(Long id) {
        this.id = id;
    }

    @Generated
    public PasswordModel(Long id, String PWD_ID, String DEFAULT_PASSWORD, String REFUND_PASWORD, String TIP_ADJUST_PASSWORD, String PRE_AUTH_PASSWORD, String BALANCE_PASSWORD, String OFFLINE_PASSWORD, String SETTLEMENT_PASSWORD, String EDITOR_PASSWORD, String VOID_PASSWORD, String MANUAL_ENTRY_PASSWORD, String CASH_ADVANCED_PASSWORD, String TERMINAL_POWERON_PASSWORD) {
        this.id = id;
        this.PWD_ID = PWD_ID;
        this.DEFAULT_PASSWORD = DEFAULT_PASSWORD;
        this.REFUND_PASWORD = REFUND_PASWORD;
        this.TIP_ADJUST_PASSWORD = TIP_ADJUST_PASSWORD;
        this.PRE_AUTH_PASSWORD = PRE_AUTH_PASSWORD;
        this.BALANCE_PASSWORD = BALANCE_PASSWORD;
        this.OFFLINE_PASSWORD = OFFLINE_PASSWORD;
        this.SETTLEMENT_PASSWORD = SETTLEMENT_PASSWORD;
        this.EDITOR_PASSWORD = EDITOR_PASSWORD;
        this.VOID_PASSWORD = VOID_PASSWORD;
        this.MANUAL_ENTRY_PASSWORD = MANUAL_ENTRY_PASSWORD;
        this.CASH_ADVANCED_PASSWORD = CASH_ADVANCED_PASSWORD;
        this.TERMINAL_POWERON_PASSWORD = TERMINAL_POWERON_PASSWORD;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPWD_ID() {
        return PWD_ID;
    }

    public void setPWD_ID(String PWD_ID) {
        this.PWD_ID = PWD_ID;
    }

    public String getDEFAULT_PASSWORD() {
        return DEFAULT_PASSWORD;
    }

    public void setDEFAULT_PASSWORD(String DEFAULT_PASSWORD) {
        this.DEFAULT_PASSWORD = DEFAULT_PASSWORD;
    }

    public String getREFUND_PASWORD() {
        return REFUND_PASWORD;
    }

    public void setREFUND_PASWORD(String REFUND_PASWORD) {
        this.REFUND_PASWORD = REFUND_PASWORD;
    }

    public String getTIP_ADJUST_PASSWORD() {
        return TIP_ADJUST_PASSWORD;
    }

    public void setTIP_ADJUST_PASSWORD(String TIP_ADJUST_PASSWORD) {
        this.TIP_ADJUST_PASSWORD = TIP_ADJUST_PASSWORD;
    }

    public String getPRE_AUTH_PASSWORD() {
        return PRE_AUTH_PASSWORD;
    }

    public void setPRE_AUTH_PASSWORD(String PRE_AUTH_PASSWORD) {
        this.PRE_AUTH_PASSWORD = PRE_AUTH_PASSWORD;
    }

    public String getBALANCE_PASSWORD() {
        return BALANCE_PASSWORD;
    }

    public void setBALANCE_PASSWORD(String BALANCE_PASSWORD) {
        this.BALANCE_PASSWORD = BALANCE_PASSWORD;
    }

    public String getOFFLINE_PASSWORD() {
        return OFFLINE_PASSWORD;
    }

    public void setOFFLINE_PASSWORD(String OFFLINE_PASSWORD) {
        this.OFFLINE_PASSWORD = OFFLINE_PASSWORD;
    }

    public String getSETTLEMENT_PASSWORD() {
        return SETTLEMENT_PASSWORD;
    }

    public void setSETTLEMENT_PASSWORD(String SETTLEMENT_PASSWORD) {
        this.SETTLEMENT_PASSWORD = SETTLEMENT_PASSWORD;
    }

    public String getEDITOR_PASSWORD() {
        return EDITOR_PASSWORD;
    }

    public void setEDITOR_PASSWORD(String EDITOR_PASSWORD) {
        this.EDITOR_PASSWORD = EDITOR_PASSWORD;
    }

    public String getVOID_PASSWORD() {
        return VOID_PASSWORD;
    }

    public void setVOID_PASSWORD(String VOID_PASSWORD) {
        this.VOID_PASSWORD = VOID_PASSWORD;
    }

    public String getMANUAL_ENTRY_PASSWORD() {
        return MANUAL_ENTRY_PASSWORD;
    }

    public void setMANUAL_ENTRY_PASSWORD(String MANUAL_ENTRY_PASSWORD) {
        this.MANUAL_ENTRY_PASSWORD = MANUAL_ENTRY_PASSWORD;
    }

    public String getCASH_ADVANCED_PASSWORD() {
        return CASH_ADVANCED_PASSWORD;
    }

    public void setCASH_ADVANCED_PASSWORD(String CASH_ADVANCED_PASSWORD) {
        this.CASH_ADVANCED_PASSWORD = CASH_ADVANCED_PASSWORD;
    }

    public String getTERMINAL_POWERON_PASSWORD() {
        return TERMINAL_POWERON_PASSWORD;
    }

    public void setTERMINAL_POWERON_PASSWORD(String TERMINAL_POWERON_PASSWORD) {
        this.TERMINAL_POWERON_PASSWORD = TERMINAL_POWERON_PASSWORD;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
