package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "RECEIPT_TABLE".
 */
@Entity
public class ReceiptTable {

    @Id(autoincrement = true)
    private Long id;
    private String RECEIPT_ID;
    private String PRINT_TIMEOUT;
    private String AUTO_PRINT;
    private String PRINTER_INTENSITY_CFG;
    private String PRINTER_CFG;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ReceiptTable() {
    }

    public ReceiptTable(Long id) {
        this.id = id;
    }

    @Generated
    public ReceiptTable(Long id, String RECEIPT_ID, String PRINT_TIMEOUT, String AUTO_PRINT, String PRINTER_INTENSITY_CFG, String PRINTER_CFG) {
        this.id = id;
        this.RECEIPT_ID = RECEIPT_ID;
        this.PRINT_TIMEOUT = PRINT_TIMEOUT;
        this.AUTO_PRINT = AUTO_PRINT;
        this.PRINTER_INTENSITY_CFG = PRINTER_INTENSITY_CFG;
        this.PRINTER_CFG = PRINTER_CFG;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRECEIPT_ID() {
        return RECEIPT_ID;
    }

    public void setRECEIPT_ID(String RECEIPT_ID) {
        this.RECEIPT_ID = RECEIPT_ID;
    }

    public String getPRINT_TIMEOUT() {
        return PRINT_TIMEOUT;
    }

    public void setPRINT_TIMEOUT(String PRINT_TIMEOUT) {
        this.PRINT_TIMEOUT = PRINT_TIMEOUT;
    }

    public String getAUTO_PRINT() {
        return AUTO_PRINT;
    }

    public void setAUTO_PRINT(String AUTO_PRINT) {
        this.AUTO_PRINT = AUTO_PRINT;
    }

    public String getPRINTER_INTENSITY_CFG() {
        return PRINTER_INTENSITY_CFG;
    }

    public void setPRINTER_INTENSITY_CFG(String PRINTER_INTENSITY_CFG) {
        this.PRINTER_INTENSITY_CFG = PRINTER_INTENSITY_CFG;
    }

    public String getPRINTER_CFG() {
        return PRINTER_CFG;
    }

    public void setPRINTER_CFG(String PRINTER_CFG) {
        this.PRINTER_CFG = PRINTER_CFG;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
