package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TABLE__REPORT".
 */
@Entity
public class TABLE_REPORT {

    @Id(autoincrement = true)
    private Long id;
    private String REPORTTABLE_ID;
    private String DETAILED_REPORT;
    private String TIP_REPORT;
    private String TOTAL_REPORT;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TABLE_REPORT() {
    }

    public TABLE_REPORT(Long id) {
        this.id = id;
    }

    @Generated
    public TABLE_REPORT(Long id, String REPORTTABLE_ID, String DETAILED_REPORT, String TIP_REPORT, String TOTAL_REPORT) {
        this.id = id;
        this.REPORTTABLE_ID = REPORTTABLE_ID;
        this.DETAILED_REPORT = DETAILED_REPORT;
        this.TIP_REPORT = TIP_REPORT;
        this.TOTAL_REPORT = TOTAL_REPORT;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getREPORTTABLE_ID() {
        return REPORTTABLE_ID;
    }

    public void setREPORTTABLE_ID(String REPORTTABLE_ID) {
        this.REPORTTABLE_ID = REPORTTABLE_ID;
    }

    public String getDETAILED_REPORT() {
        return DETAILED_REPORT;
    }

    public void setDETAILED_REPORT(String DETAILED_REPORT) {
        this.DETAILED_REPORT = DETAILED_REPORT;
    }

    public String getTIP_REPORT() {
        return TIP_REPORT;
    }

    public void setTIP_REPORT(String TIP_REPORT) {
        this.TIP_REPORT = TIP_REPORT;
    }

    public String getTOTAL_REPORT() {
        return TOTAL_REPORT;
    }

    public void setTOTAL_REPORT(String TOTAL_REPORT) {
        this.TOTAL_REPORT = TOTAL_REPORT;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
