package com.mobileeftpos.android.eftpos.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TRACE_MODEL".
 */
@Entity
public class TraceModel {

    @Id(autoincrement = true)
    private Long id;
    private String TRACE_UNIQUE_ID;
    private String SYSTEM_TRACE;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TraceModel() {
    }

    public TraceModel(Long id) {
        this.id = id;
    }

    @Generated
    public TraceModel(Long id, String TRACE_UNIQUE_ID, String SYSTEM_TRACE) {
        this.id = id;
        this.TRACE_UNIQUE_ID = TRACE_UNIQUE_ID;
        this.SYSTEM_TRACE = SYSTEM_TRACE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTRACE_UNIQUE_ID() {
        return TRACE_UNIQUE_ID;
    }

    public void setTRACE_UNIQUE_ID(String TRACE_UNIQUE_ID) {
        this.TRACE_UNIQUE_ID = TRACE_UNIQUE_ID;
    }

    public String getSYSTEM_TRACE() {
        return SYSTEM_TRACE;
    }

    public void setSYSTEM_TRACE(String SYSTEM_TRACE) {
        this.SYSTEM_TRACE = SYSTEM_TRACE;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
