package com.mobileeftpos.android.eftpos.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRACE_MODEL".
*/
public class TraceModelDao extends AbstractDao<TraceModel, Long> {

    public static final String TABLENAME = "TRACE_MODEL";

    /**
     * Properties of entity TraceModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TRACE_UNIQUE_ID = new Property(1, String.class, "TRACE_UNIQUE_ID", false, "TRACE__UNIQUE__ID");
        public final static Property SYSTEM_TRACE = new Property(2, String.class, "SYSTEM_TRACE", false, "SYSTEM__TRACE");
    }


    public TraceModelDao(DaoConfig config) {
        super(config);
    }
    
    public TraceModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRACE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRACE__UNIQUE__ID\" TEXT," + // 1: TRACE_UNIQUE_ID
                "\"SYSTEM__TRACE\" TEXT);"); // 2: SYSTEM_TRACE
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRACE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TraceModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String TRACE_UNIQUE_ID = entity.getTRACE_UNIQUE_ID();
        if (TRACE_UNIQUE_ID != null) {
            stmt.bindString(2, TRACE_UNIQUE_ID);
        }
 
        String SYSTEM_TRACE = entity.getSYSTEM_TRACE();
        if (SYSTEM_TRACE != null) {
            stmt.bindString(3, SYSTEM_TRACE);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TraceModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String TRACE_UNIQUE_ID = entity.getTRACE_UNIQUE_ID();
        if (TRACE_UNIQUE_ID != null) {
            stmt.bindString(2, TRACE_UNIQUE_ID);
        }
 
        String SYSTEM_TRACE = entity.getSYSTEM_TRACE();
        if (SYSTEM_TRACE != null) {
            stmt.bindString(3, SYSTEM_TRACE);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TraceModel readEntity(Cursor cursor, int offset) {
        TraceModel entity = new TraceModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // TRACE_UNIQUE_ID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // SYSTEM_TRACE
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TraceModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTRACE_UNIQUE_ID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSYSTEM_TRACE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TraceModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TraceModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TraceModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
